baseURL = 'https://schellenberg.3.github.io'
languageCode = 'en-us'
title = 'Andrew Schllenberg'
copyright = 'Copyright © 2023 Andrew Schellenberg'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      # This setting allows inlining <script> and <style> tags in markdown,
      # which is useful and required to use Prism plugins, but may be dangerous
      # if the content isn't trustworthy.
      unsafe = true

[build]
  # The theme enables writeStats which is required for PurgeCSS
  _merge = "deep"

# This hopefully will be simpler in the future.
# See: https://github.com/schnerring/hugo-theme-gruvbox/issues/16
[module]
  [[module.imports]]
    path = "github.com/schnerring/hugo-theme-gruvbox"
  [[module.imports]]
    path = "github.com/schnerring/hugo-mod-json-resume"
    [[module.imports.mounts]]
      source = "data"
      target = "data"
    [[module.imports.mounts]]
      source = "layouts"
      target = "layouts"
    [[module.imports.mounts]]
      source = "assets/css/json-resume.css"
      target = "assets/css/critical/44-json-resume.css"
  [[module.mounts]]
    # required by hugo-mod-json-resume
    source = "node_modules/simple-icons/icons"
    target = "assets/simple-icons"
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "layouts"
    target = "layouts"
  [[module.mounts]]
    source = "static"
    target = "static"
  [[module.mounts]]
    source = "node_modules/prismjs"
    target = "assets/prismjs"
  [[module.mounts]]
    source = "node_modules/prism-themes/themes"
    target = "assets/prism-themes"
  [[module.mounts]]
    source = "node_modules/typeface-fira-code/files"
    target = "static/fonts"
  [[module.mounts]]
    source = "node_modules/typeface-roboto-slab/files"
    target = "static/fonts"
  [[module.mounts]]
    source = "node_modules/@tabler/icons/icons"
    target = "assets/tabler-icons"

[imaging]
  # JPEG and WebP quality
  quality = 90

[params]
    [params.logo]
      text = "Schellenberg.GitHub.io"
      url = "/"

  [params.prism]
    languages = [
      "bash",
      "c",
      "clike",
      "cpp",
      "git",
      "ignore",
      "json",
      "markdown",
      "matlab",
      "mermaid",
      "powershell",
      "python",
      "yaml",
      "json"
    ]
    plugins = [
      "normalize-whitespace",
      "toolbar",
      "copy-to-clipboard",
      "command-line"
    ]

[menu]
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    pageRef = "/blog"
    weight = 10
  [[menu.main]]
    identifier = "cv"
    name = "CV"
    pageRef = "/cv"
    weight = 30
  [[menu.main]]
    identifier = "about"
    name = "About"
    pageRef = "/about"
    weight = 40